name = "IFTDuals"
uuid = "e48d2a1f-af84-496e-b4fe-d99c19dbdf31"
authors = ["Garren Hermanus <garren382@gmail.com>"]
version = "0.1.3"

[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
IFTDualsStaticArraysExt = "StaticArrays"

[compat]
DifferentiationInterface = "0.6, 0.7"
ForwardDiff = "1"
LinearAlgebra = "1"
StaticArrays = "^1.5.9"
julia = "1.10"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
